#!/usr/bin/env python3
"""Generate the prompt_templates table + seed migration from the .md sources.

The database is the source of truth for prompt bodies at runtime; the .md files
under ``prompts/`` and ``evals/judge/`` are the human-editable seed source. This
script reads them, computes the sha256 + byte length the editor expects, and
emits a self-contained Supabase migration that both ``supabase db reset`` (local)
and ``supabase db push`` (prod) can apply.

Run from the repo root::

    python scripts/gen_prompt_seed.py

It overwrites ``supabase/migrations/20260529000001_prompt_templates.sql``.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PROMPTS_DIR = REPO_ROOT / "prompts"
JUDGE_DIR = REPO_ROOT / "evals" / "judge"
OUT_PATH = REPO_ROOT / "supabase" / "migrations" / "20260529000001_prompt_templates.sql"

# Dollar-quote tag for embedding arbitrary body text in SQL safely.
_DQ = "$pt$"

# template_id -> (category, source path). Order is stable for deterministic diffs.
_AGENTS = [
    "audit",
    "gap_analysis",
    "outline",
    "outline_create_mode",
    "writer_small_refresh",
    "writer_full_rewrite",
    "writer_create",
    "topic_gen",
    "topic_dedup",
    "topic_hot",
]
_PARTIALS = [
    "_writer_brand_block",
    "_writer_schema",
    "_writer_seo",
    "_writer_refine_notes",
    "_writer_output_format_tail",
]
_JUDGES = {
    "judge_brand_voice": "brand_voice.md",
    "judge_coverage": "coverage.md",
    "judge_citation_alignment": "citation_alignment.md",
    "judge_hk_localisation": "hk_localisation.md",
}


def _registry() -> list[tuple[str, str, Path]]:
    """Return (template_id, category, source_path) for every template."""
    rows: list[tuple[str, str, Path]] = []
    for tid in _AGENTS:
        rows.append((tid, "agent", PROMPTS_DIR / f"{tid}.md"))
    for tid in _PARTIALS:
        rows.append((tid, "partial", PROMPTS_DIR / f"{tid}.md"))
    for tid, fname in _JUDGES.items():
        rows.append((tid, "judge", JUDGE_DIR / fname))
    return rows


def _sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _values_clause() -> str:
    lines: list[str] = []
    for tid, category, path in _registry():
        if not path.exists():
            raise FileNotFoundError(f"prompt source missing: {path}")
        body = path.read_text(encoding="utf-8")
        if _DQ in body:
            raise ValueError(f"body of {tid} contains the dollar-quote tag {_DQ!r}")
        sha = hashlib.sha256(body.encode("utf-8")).hexdigest()
        nbytes = len(body.encode("utf-8"))
        lines.append(
            f"  ({_sql_literal(tid)}, {_sql_literal(category)}, "
            f"{_sql_literal(path.name)}, {_DQ}{body}{_DQ}, "
            f"{_sql_literal(sha)}, {nbytes})"
        )
    return ",\n".join(lines)


def build_migration() -> str:
    header = """\
-- AUTO-GENERATED by scripts/gen_prompt_seed.py -- do not edit by hand.
-- Live prompt-template store. The database is the source of truth at runtime;
-- the .md files under prompts/ and evals/judge/ are the seed source. Seeds run
-- on both `supabase db reset` (local) and `supabase db push` (prod), so prod is
-- populated without relying on seed.sql. ON CONFLICT keeps re-runs idempotent.
-- RLS + grants live in the companion *_prompt_templates_rls.sql migration.

CREATE TABLE IF NOT EXISTS content_tool.prompt_templates (
    template_id  character varying NOT NULL,
    category     character varying NOT NULL,
    filename     character varying NOT NULL,
    body         character varying NOT NULL,
    sha256       character varying NOT NULL,
    bytes        integer NOT NULL,
    updated_at   timestamp with time zone DEFAULT now() NOT NULL,
    updated_by   character varying
);

ALTER TABLE content_tool.prompt_templates OWNER TO postgres;

ALTER TABLE ONLY content_tool.prompt_templates
    ADD CONSTRAINT prompt_templates_pkey PRIMARY KEY (template_id);

CREATE INDEX IF NOT EXISTS prompt_templates_category_idx
    ON content_tool.prompt_templates USING btree (category);

INSERT INTO content_tool.prompt_templates
    (template_id, category, filename, body, sha256, bytes)
VALUES
"""
    return header + _values_clause() + "\nON CONFLICT (template_id) DO NOTHING;\n"


def main() -> None:
    OUT_PATH.write_text(build_migration(), encoding="utf-8")
    n = len(_registry())
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} ({n} templates)")


if __name__ == "__main__":
    main()
